name: Elixir FreeBSD Release

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: macos-12
    name: Elixir FreeBSD Release
    env:
      APPLICATION: freebsd_test
      RELEASE_PATH: _build/prod/rel

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Prepare release
        uses: cross-platform-actions/action@v0.15.0
        env:
          MIX_ENV: prod
        timeout-minutes: 20
        with:
          environment_variables: RELEASE_PATH APPLICATION MIX_ENV
          operating_system: freebsd
          version: '13.2'
          run: |
            sudo pkg install -y elixir erlang git node npm
            mix local.rebar --force
            mix local.hex --force
            mix deps.get
            cd assets && npm install
            mix assets.deploy
            mix compile
            mix release
            set REVISION=`git describe`
            tar -zcvf $APPLICATION-$REVISION.tar.gz -C $RELEASE_PATH .

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.tar.gz'
